import pandas as pd
df1 = pd.read_csv('customer_demographics.csv')
df2 = pd.read_csv('user_activity_logs.csv')
df3 = pd.read_csv('customer_support.csv')
df4 = pd.merge(df1, df2, on='customer_id')
df4 = pd.merge(df4, df3, on='customer_id')
df4['age'].fillna(df4['age'].mean(), inplace=True)
df4['page_views'].fillna(df4['page_views'].mean(), inplace=True)
df4['interaction_duration'].fillna(df4['interaction_duration'].mean(), inplace=True)
df4['support_tickets'].fillna(0, inplace=True)
df4['gender'].fillna(df4['gender'].mode()[0], inplace=True)
df4['location'].fillna(df4['location'].mode()[0], inplace=True)
df4.drop_duplicates(inplace=True)
print("Unified dataset:")
print(df4.head())
